export enum ColegiaturaSearchActionType {
  COLEGIATURA_LOADING = "COLEGIATURA_LOADING",
  COLEGIATURA_LOAD_SUCCESS = "COLEGIATURA_LOAD_SUCCESS",
  COLEGIATURA_LOAD_FAILURE = "COLEGIATURA_LOAD_FAILURE",
}
